ControlNorte/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cliente/', include('cliente.urls', namespace='cliente')),
    path('hpinicial/', include('hpinicial.urls', namespace='homepageinicial')),
    path('', include('financeiro.urls', namespace='fianceiro')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cliente/urls.py
from django.urls import path, include
from cliente import views
from .views import *

app_name = 'cliente'

urlpatterns = [
    path('', Cliente.as_view(), name='cliente'),
    path('<int:pk>/', Destalhesclientes.as_view(), name='detalhesclientes'),
    path('cadastrarcliente/', cadastrarcliente, name='cadastrarcliente'),
    path('editar/<int:pk>/', Editarcliente.as_view(template_name='editarcliente.html'), name='editarcliente'),
    path('download_modelo_importacao/', views.download_modelo_importacao_cadastro_cliente, name='download_modelo_importacao_cadastro_cliente'),
]

financeiro/urls.py
from dask.dataframe.io.demo import names
from django.urls import path, re_path
from . import views
from .views import *
from .api_pluggy import handle_item_data, recice_webhook
from .teste import download_modelo_importacao_cadastro_subcategoria, download_modelo_importacao_cadastro_centrodecusto, download_modelo_importacao_cadastro_regras, aplicar_regras_em_transicoes

# from django.contrib.auth import views as auth_view

app_name = 'financeiro'

urlpatterns = [
    path('', financeiro_view, name='financeiro'),
    path('financeirocliente/<int:pk>/', financeirocliente, name='financeirocliente'),

    path('financeirocliente/caixa/', caixa, name='caixa'),
    path('financeirocliente/movimentacao/<str:banco>', movimentacao, name='movimentacao'),

    path('financeirocliente/dre/', dre, name='dre'),
    path('financeirocliente/dashboard/', dashboard, name='dashboard'),

    path('financeirocliente/orcamento/', orcamento, name='orcamento'),
    path('financeirocliente/orcamento/cadastrar', cadastrarorcamento, name='cadastrarorcamento'),

    path('financeirocliente/contas/', contas, name='contas'),


    path('financeirocliente/maisopicoes/', maisopicoes, name='maisopicoes'),

    path('financeirocliente/maisopicoes/banco/', banco, name='banco'),
    path('financeirocliente/maisopicoes/banco/editar/<int:id>', editarbanco, name='editarbanco'),
    path('financeirocliente/maisopicoes/banco/saldo/<int:id>', bancosaldo, name='bancosaldo'),

    path('financeirocliente/maisopicoes/categoria/', categoria, name='categoria'),
    path('financeirocliente/maisopicoes/categoria/editar/<int:id>', editarcategoria, name='editarcategoria'),

    path('financeirocliente/maisopicoes/subcategoria/', subcategoria, name='subcategoria'),
    path('financeirocliente/maisopicoes/subcategoria/editar/<int:id>', editarsubcategoria, name='editarsubcategoria'),

    path('financeirocliente/maisopicoes/centrocusto/', centrocusto, name='centrocusto'),
    path('financeirocliente/maisopicoes/centrocusto/editar/<int:id>', editarcentrocusto, name='editarcentrocusto'),

    path('financeirocliente/maisopicoes/regra/', regra, name='regra'),
    path('financeirocliente/maisopicoes/regra/editar/<int:id>', editarregra, name='editarregra'),

    path('save-data/', salvar_movimentacao, name='save_data_url'),
    path('save-data-rule/', salvar_regra_usando_movimentacao, name='save_data_url_rule'),
    path('transf/', transf, name='transf'),
    path('delete/', deletar_movimentacao, name='delete'),
    path('edit_movimentacao/', views.edit_movimentacao, name='edit_movimentacao'),
    path('delete_movimentacao/<int:id>/', views.delete_movimentacao, name='delete_movimentacao'),
    path('get_movimentacao/<int:id>/', views.get_movimentacao, name='get_movimentacao'),
    path('exportar-excel/<int:tenant>/<int:cliente>', views.export_to_excel, name='export_to_excel'),

    path('api/item-data/', handle_item_data, name='handle_item_data'),
    path('recive-webhook/', recice_webhook, name='recive_webhook'),

    path('download_modelo_importacao_sb/', download_modelo_importacao_cadastro_subcategoria, name='download_modelo_importacao_cadastro_subcategoria'),
    path('download_modelo_importacao_cc/', download_modelo_importacao_cadastro_centrodecusto, name='download_modelo_importacao_cadastro_centrodecusto'),
    path('download_modelo_importacao_r/', download_modelo_importacao_cadastro_regras, name='download_modelo_importacao_cadastro_regras'),

    path('aplicar-regras/<str:banco>/<str:cliente>/<str:tenant>/', aplicar_regras_em_transicoes, name='aplicar_regras')
]

financeiro/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from .exibicoes import *
from .teste import *

from django.http import HttpResponse
from openpyxl import load_workbook
from openpyxl.styles import PatternFill, Font, Alignment
import pandas as pd
import io


@login_required
def financeiro_view(request):
    ### HOMEPAGE FINANCEIRO ###

    print(request.tenant)
    #if request.tenant:
    clientes = cadastro_de_cliente.objects.for_tenant(request.tenant).filter(ativo=True).order_by('razao_social')

    #else:
    
        #clientes = []
        #dadoscliente = None

    context = {
        'object_list': clientes,
        #'dadoscliente': dadoscliente,
    }

    return render(request, 'visualizacao/homepagefinanceiro.html', context)

def financeirocliente(request, pk):
    ### TELA DE RESUMO DOS DADOS FINANCEIRO DO CLIENTE ###

    dadoscliente = cadastro_de_cliente.objects.for_tenant(request.tenant).get(pk=pk)
    request.session['dadoscliente'] = pk  # Armazena o pk do cliente na sessão

    ### RESUMO DA DRE/DASHBOARD/ORÇAMENTO/CONTAS PAGAS E RECEBIDAS DO MÊS CORRENTE ###

    ### RESUMO DA DRE DO MÊS CORRENTE ###
    if request.method == 'GET':
        dreresumo = dreresumida(cliente=dadoscliente)

    ### TODO FAZER O BACKEND E FRONTEND DO RESUMO DO DASHBOARD/ORÇAMENTO/CONTAS PAGAS E RECEBIDAS

    ### CONTEXTS FINANCEIRO CLIENTE ###
    context = {
        'dadoscliente': dadoscliente,
        'dreresumo': dreresumo,

    }

    return render(request, 'visualizacao/financeirocliente.html', context)


def caixa(request):
    ### EXIBIR O GRÁFICO COM O FLUXO DE CAIXA DE TODOS OS BANCOS E COM OS ULTIMOS 3 MESES E OS PRÓXIMOS 3 MESES ###
    ### TODO COLOCAR UM GRÁFICO INTERATIVO DO FLUXO DE CAIXA IGUAL AO DO NIBO, COM OS CHECKS PARA SELECIONAR OS BANCOS E A PROJEÇÃO DOS VALORES

    pk = request.session.get('dadoscliente')

    if not pk:
        return redirect('/')  # Redireciona se dadoscliente não estiver disponível

    dadoscliente = cadastro_de_cliente.objects.for_tenant(request.tenant).get(pk=pk)

    bancos = BancosCliente.objects.for_tenant(request.tenant).filter(ativo='True', cliente=dadoscliente).order_by('banco')

    ### CONTEXTS CAIXA ###
    context = {
        'dadoscliente': dadoscliente,
        'bancos': bancos,
    }

    return render(request, 'visualizacao/caixa.html', context)


@csrf_exempt

def export_to_excel(request, tenant, cliente):
    from .models import MovimentacoesCliente  # Certifique-se de ajustar para o nome correto do model

    dadoscliente = cadastro_de_cliente.objects.for_tenant(request.tenant).get(pk=cliente)
    movimentacoes = MovimentacoesCliente.objects.for_tenant(request.tenant).filter(cliente=dadoscliente)

    df_hist = pd.DataFrame(list(movimentacoes.values(
        'descricao',
        'detalhe',
        'valor',
        'banco__banco',
        'centrodecusto__nome',
        'categoria__nome',
        'subcategoria__nome',
        'data',
    )))

    if df_hist.empty:
        return HttpResponse("Sem dados para exportar", content_type="text/plain")

    df_hist.rename(columns={
        'descricao': 'Descrição',
        'detalhe': 'Detalhe',
        'valor': 'Valor categoria/centro de custo',
        'banco__banco': 'Conta',
        'centrodecusto__nome': 'Centro de Custo',
        'categoria__nome': 'Categoria',
        'subcategoria__nome': 'Subcategoria',
        'data': 'Data de pagamento'
    }, inplace=True)

    df_hist['Descrição_normalizada'] = df_hist['Descrição'].astype(str).str.lower().str.strip()
    df_hist['Categoria_normalizada'] = df_hist['Categoria'].astype(str).str.lower().str.strip()
    descricoes_ambiguas = df_hist.groupby('Descrição_normalizada')['Categoria_normalizada']\
        .nunique().loc[lambda x: x > 1].index.tolist()

    colunas_template = [
        'Tipo de transação', 'Nome do contato', 'Descrição', 'Categoria', 'Valor',
        'Vencimento', 'Previsto para', 'Competência', 'Centro de custo',
        'Favorito', 'Tipo de contato', 'Referência', 'Conta',
        'Data pag/rec/transferência', 'Anotação', 'Status_Sugestao'
    ]

    linhas_convertidas = []
    for row in df_hist.itertuples(index=False):
        valor = getattr(row, 'Valor categoria/centro de custo', 0)
        descricao = str(getattr(row, 'Descrição', '')).strip()
        descricao_norm = descricao.lower()

        nova_linha = {
            'Tipo de transação': 'Pagamento' if valor < 0 else 'Recebimento',
            'Nome do contato': 'Cliente',
            'Descrição': descricao,
            'Categoria': getattr(row, 'Categoria', ''),
            'Valor': abs(valor),
            'Vencimento': '',
            'Previsto para': '',
            'Competência': '',
            'Centro de custo': getattr(row, 'Centro de Custo', ''),
            'Favorito': 'Não',
            'Tipo de contato': 'Fornecedor',
            'Referência': getattr(row, 'Detalhe', ''),
            'Conta': getattr(row, 'Conta', ''),
            'Data pag/rec/transferência': getattr(row, 'Data de pagamento', ''),
            'Anotação': '',
            'Status_Sugestao': 'Requer Revisão' if descricao_norm in descricoes_ambiguas else 'Sugerido'
        }
        linhas_convertidas.append(nova_linha)

    df_convertido = pd.DataFrame(linhas_convertidas, columns=colunas_template)

    # Criação do Excel com formatação
    output = io.BytesIO()
    writer = pd.ExcelWriter(output, engine='openpyxl')
    df_convertido.to_excel(writer, index=False, sheet_name='Exportação')
    writer.close()

    wb = load_workbook(filename=output)
    ws = wb.active

    azul = PatternFill(start_color="538DD5", end_color="538DD5", fill_type="solid")
    for cell in ws[1]:
        cell.fill = azul
        cell.font = Font(bold=True)
        cell.alignment = Alignment(horizontal="center", vertical="center")

    # Enviar como resposta HTTP
    final_output = io.BytesIO()
    wb.save(final_output)
    final_output.seek(0)

    response = HttpResponse(
        final_output,
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )
    response['Content-Disposition'] = 'attachment; filename=exportacao_pagose_recebidos.xlsx'
    return response

def movimentacao(request, banco):
    ### EXIBE AS MOVIMENTAÇÕES DOS CLIENTES FILTADAS POR BANCO E CADASTRAR MOVIMENTAÇÕES ###

    pk = request.session.get('dadoscliente')
    if not pk:
        return redirect('/')  # Redireciona se dadoscliente não estiver disponível

    dadoscliente = cadastro_de_cliente.objects.for_tenant(request.tenant).get(pk=pk)
    bancos = BancosCliente.objects.for_tenant(request.tenant).filter(ativo='True', cliente=dadoscliente).order_by('banco')
    bancoatual = BancosCliente.objects.for_tenant(request.tenant).get(ativo='True', cliente=dadoscliente, banco=banco)
    request.session['bancoatual'] = bancoatual.id
    mesatual = datetime.now().month
    mesatual = mes(mesatual)

    exbextrato = 'Não tem movimentações registradas nesse mês!'
    grafico = ''
    erroentrada = ''
    errosaida = ''
    df = ''
    form = UploadFileForm(request.POST, request.FILES)

    ### IMPORTAR PLNILHA DE EXCEL (FORMATO: DATA/DESCRIÇÃO/VALOR) ###
    if form.is_valid():
        form.save()
        file = request.FILES['file']
        df = importar_arquivo_excel(file, cliente=dadoscliente, banco=bancoatual, request=request)


    ### FUNÇÕES DE LANÇAR MANUALMENTE UMA ENTRADA, SAÍDA OU TRANSFERENCIA E RENDERIZAR O GRÁFICO ###
    if request.method == 'POST':
        dados = request.POST.dict()

        ### FUNÇÃO DE RENDERIZAR O GRÁFICO ###
        if dados.get('tipo') == 'mes':
            mesfiltro = messtr(dados.get('mesfiltro'))
            mesatual = dados.get('mesfiltro')
            grafico = gerar_grafico(cliente=dadoscliente, banco=bancoatual.id, mes=mesfiltro)
            exbextrato = extrato(cliente=dadoscliente, banco=bancoatual.id, mes=mesfiltro)

        ### FUNÇÃO DE CADASTRO ENTRADA MANUALMENTE ###
        elif dados.get('tipo') == 'entrada':
            valor = float(dados.get('valor').replace(',', '.'))

            ### SALVA A ENTRADA NO BC MovimentacoesCliente ###
            if valor >= 0:
                movimentacoes = MovimentacoesCliente.objects.create(
                    tenant=request.tenant,
                    cliente=dadoscliente,
                    banco=BancosCliente.objects.get(id=bancoatual.id),
                    data=dados.get('data'),
                    descricao=dados.get('descricao'),
                    detalhe=dados.get('detalhe'),
                    valor=valor,
                    categoria=Categoria.objects.get(id=dados.get("categoria")),
                    subcategoria=SubCategoria.objects.get(id=dados.get("subcategoria")),
                    centrodecusto=CentroDeCusto.objects.get(id=dados.get("centrocusto")),

                )

                movimentacoes.save()

                ### ALTERA O SALDO DO BANCO RESPCTO DE ACORDO COM A MOVIMENTACAO CADASTRADA ANTERIORMENTE ###
                alteracaosaldo(banco=bancoatual.id, cliente=dadoscliente.id, data=dados.get('data'), request=request)

            else:
                erroentrada = 'Valor de Entrada Tem que ser maior que 0,0'

        ### FUNÇÃO DE CADASTRO SAÍDA MANUALMENTE ###
        elif dados.get('tipo') == 'saida':

            ### FUNÇÃO DE CONVERTER VALORES CADASTRADOS ###
            if float(dados.get('valor').replace(',', '.')) <= 0:
                valor = float(dados.get('valor').replace(',', '.'))

            else:
                valor = float(dados.get('valor').replace(',', '.')) * - 1.0

            ### SALVA A SAÍDA NO BC MovimentacoesCliente ###
            movimentacoes = MovimentacoesCliente.objects.create(
                tenant=request.tenant,

financeiro/templates/cadastros/banco.html
{% extends 'base.html' %}

{% block titulo %}
Financeiro | {{ dadoscliente }}
{% endblock %}

{% block head %}
<meta name="csrf-token" content="{{ csrf_token }}">
{% endblock %}

{% block content %}
<body>
<main class="py-20 px-10">

        <div class="flex felx-nowrap justify-between items-center pt-4 pb-3 px-4">
        <div class="text-3xl text-violet-900 flex justify-between">{{ dadoscliente }}</div>
            <a href="{% url 'financeiro:maisopicoes' %}">
                <div class="text-lg text-violet-900 flex justify-between items-center">
                    <ion-icon name="ellipsis-vertical-sharp"></ion-icon> Mais opções
                </div>
            </a>
        </div>

    <div>
            <div class=" container pt-2 px-20 flex justify-between">
                <div class="text-lg text-violet-900 hover:border-b-4 border-violet-300 p-2"><a href="{% url 'financeiro:financeirocliente' dadoscliente.pk %}"><ion-icon name="arrow-back-outline"></ion-icon></a></div>
                <div class="text-lg text-violet-900 hover:border-b-4 border-violet-300 p-2"><a href="{% url 'financeiro:maisopicoes' %}">Dados</a></div>
                <div class="text-lg text-violet-900 border-b-4 border-violet-800 p-2"><a href="{% url 'financeiro:banco' %}">Bancos</a></div>
                <div class="text-lg text-violet-900 hover:border-b-4 border-violet-300 p-2"><a href="{% url 'financeiro:categoria' %}">Categorias</a></div>
                <div class="text-lg text-violet-900 hover:border-b-4 border-violet-300 p-2"><a href="{% url 'financeiro:subcategoria' %}">Sub-Categorias</a></div>
                <div class="text-lg text-violet-900 hover:border-b-4 border-violet-300 p-2"><a href="{% url 'financeiro:centrocusto' %}">Centro de Custo</a></div>
                <div class="text-lg text-violet-900 hover:border-b-4 border-violet-300 p-2"><a href="{% url 'financeiro:regra' %}">Regras</a></div>
            </div>
            <hr>
            <div class="p-4">
                <div class="container w-2/5 p-4 bg-violet-100 rounded">
                    <div class="flex flex-nowrap justify-between content-center">
                        <div class="py-2 px-4 text-2xl text-violet-900 text-center">Novo Banco</div>
                         <div>
                             <a href="#">
                                <button class="bg-transparent text-violet-700 font-semibold hover:text-black px-4 pt-1 rounded">
                                   <ion-icon name="push-outline"></ion-icon> Importar
                                </button>
                            </a>
                         </div>
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="text-violet-800">
                            <div class="row g-3">
                            <div>
                                <label for="nomebanco">Banco: </label>
                                <input type="text" id="nomebanco" name="banco" class="form-control" placeholder="Banco" required>
                                <br>
                                <label for="agenciabanco">Agência: </label>
                                <input type="number" id="agenciabanco" name="agencia" class="form-control" placeholder="Agência" required>
                                <br>
                                <label for="contabanco">Conta: </label>
                                <input type="number" id="contabanco" name="conta" class="form-control" placeholder="Conta" required>
                                <br>
                                <label for="digitobanco">Dígito: </label>
                                <input type="number" id="digitobanco" name="digito" class="form-control" placeholder="Dígito" required>
                                <br>
                                <label for="ativobanco">Ativo: </label>
                                <input type="checkbox" id="ativobanco" name="ativo" value="True">
                            </div>
                            <div class="col-start-3 flex justify-between">
                                <button class="bg-violet-600 hover:bg-violet-800 text-white py-1 my-2 px-3 md:text-lg rounded-md" id="connectButton">Conectar Conta</button>
                                <button class="bg-violet-600 hover:bg-violet-800 text-white py-1 my-2 px-3 md:text-lg rounded-md" type="submit">Salvar</button>
                            </div>
                            </div>
                        </div>
                    </form>

                </div>
                <div class="container w-9/10 p-4">
                <div class="text-2xl text-violet-900 font-semibold flex justify-between pb-2">
                    Bancos Cadastrados
                </div>
                <hr>
                <table class="table-auto w-full text-left">
                    <thead>
                        <tr class="text-violet-900">
                            <th class="py-2 px-2">Banco</th>
                            <th class="py-2 px-2">Agência</th>
                            <th class="py-2 px-2">Conta</th>
                            <th class="py-2 px-2">Ativo</th>
                            <th class="py-2 px-2">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for banco in bancos %}
                        <tr class="border-b">
                            <td class="py-2 px-2 text-gray-700">{{ banco.banco }}</td>
                            <td class="py-2 px-2 text-gray-700">{{ banco.agencia }}</td>
                            <td class="py-2 px-2 text-gray-700">{{ banco.conta }} - {{ banco.digito }}</td>
                            <td class="py-2 px-2 text-gray-700">{% if banco.ativo %} Sim {% else %} Não {% endif %}</td>
                            <td class="py-2 px-2 flex justify-center">
                                <button class="bg-violet-600 hover:bg-violet-800 text-white py-1 my-2 px-3 md:text-lg rounded-md">
                                    <a href="{% url 'financeiro:bancosaldo' banco.pk %}">Cadastrar Saldo Inicial</a>
                                </button>
                                <button class="bg-transparent text-violet-700 hover:text-black px-4">
                                    <a href="{% url 'financeiro:editarbanco' banco.pk %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                            <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z"/>
                                        </svg>
                                    </a>
                                </button>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>

    </div>

    <script src="https://cdn.pluggy.ai/pluggy-connect/v2.8.2/pluggy-connect.js"></script>
    <script>
      // Seleciona o botão pelo ID
      const connectButton = document.getElementById('connectButton');
      // Adiciona um evento de clique no botão
      connectButton.addEventListener('click', () => {
        // Realiza a requisição fetch ao clicar no botão
        fetch('https://pluggy-connect-token-three.vercel.app/api/token', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            options: {
              clientUserId: String({{ pk }}),
            },
          }),
        })
          .then((response) => response.json())
          .then(({ accessToken }) => {
            const pluggyConnect = new PluggyConnect({
              connectToken: accessToken,
              includeSandbox: true,
              onSuccess: (itemData) => {
              // Enviar itemData para o backend
              fetch('/api/item-data/', {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json',
                  // Adicione o cabeçalho CSRF se necessário
                  'X-CSRFToken': getCookie('csrftoken'),
                },
                body: JSON.stringify({
                    itemData: itemData,
                    accessToken: accessToken,
                }), // Envia os dados para a view no Django
              })
                .then((res) => res.json())
                .then((data) => {
                  console.log('Resposta do backend:', data);
                })
                .catch((err) => {
                  console.error('Erro ao enviar dados para o backend:', err);
                });
            },
              onError: (error) => {
                // TODO: Implementar lógica para erro na conexão
                console.error('Erro ao conectar com o Pluggy:', error);
              },
            });
            pluggyConnect.init();
          })
          .catch((error) => {
            console.error('Erro na requisição do token:', error);
          });
      });

        function getCookie(name) {
          const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
          return csrfToken || '';
        }

        // Função para obter o cookie CSRF
        function getCookie(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
              const cookie = cookies[i].trim();
              if (cookie.substring(0, name.length + 1) === name + '=') {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
              }
            }
          }
          return cookieValue;
        }
    </script>

</main>
</body>



{% endblock %}

financeiro/templates/cadastros/cadastrarorcamento.html
{% extends 'base.html' %}

{% block titulo %}
Financeiro | {{ dadoscliente }}
{% endblock %}

{% block content %}
<main class="py-20 px-10">

        <div class="flex felx-nowrap justify-between items-center pt-4 pb-3 px-4">
        <div class="text-3xl text-violet-900 flex justify-between">{{ dadoscliente }}</div>
            <a href="{% url 'financeiro:maisopicoes' %}">
                <div class="text-lg text-violet-900 flex justify-between items-center">
                    <ion-icon name="ellipsis-vertical-sharp"></ion-icon> Mais opções
                </div>
            </a>
        </div>
        <section id="cadastrarorçamentosection">
            <div class=" container pt-2 px-20 flex justify-between">
                <div class="text-lg text-violet-900 hover:border-b-4 border-violet-300 p-2"><a href="{% url 'financeiro:financeirocliente' dadoscliente.pk %}">Resumo</a></div>
                <div class="text-lg text-violet-900 hover:border-b-4 border-violet-300 p-2"><a href="{% url 'financeiro:caixa' %}">Caixa</a></div>
                <div class="text-lg text-violet-900 hover:border-b-4 border-violet-300 p-2"><a href="{% url 'financeiro:dre' %}">DRE</a></div>
                <div class="text-lg text-violet-900 hover:border-b-4 border-violet-300 p-2"><a href="{% url 'financeiro:dashboard' %}">Dashboard</a></div>
                <div class="text-lg text-violet-900 border-b-4 border-violet-800 p-2"><a href="{% url 'financeiro:orcamento' %}">Orçamento</a></div>
                <div class="text-lg text-violet-900 hover:border-b-4 border-violet-300 p-2"><a href="{% url 'financeiro:contas' %}">Pagos e Recebido</a></div>
            </div>
            <hr>
            <div class="container w-4/5">
                essa é a pagina de cadastra orçamento
            </div>
        </section>
</main>
{% endblock %}