ControlNorte/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cliente/', include('cliente.urls', namespace='cliente')),
    path('hpinicial/', include('hpinicial.urls', namespace='homepageinicial')),
    path('', include('financeiro.urls', namespace='fianceiro')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cliente/urls.py
from django.urls import path, include
from cliente import views
from .views import *

app_name = 'cliente'

urlpatterns = [
    path('', Cliente.as_view(), name='cliente'),
    path('<int:pk>/', Destalhesclientes.as_view(), name='detalhesclientes'),
    path('cadastrarcliente/', cadastrarcliente, name='cadastrarcliente'),
    path('editar/<int:pk>/', Editarcliente.as_view(template_name='editarcliente.html'), name='editarcliente'),
    path('download_modelo_importacao/', views.download_modelo_importacao_cadastro_cliente, name='download_modelo_importacao_cadastro_cliente'),
]

hpinicial/urls.py
from django.urls import path, reverse_lazy
from .views import Perfil, Criarconta, Editarperfil
from django.contrib.auth import views as auth_view

app_name = 'homepageinicial'

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='logged_out.html'), name='logout'),
    path('perfil/<int:pk>', Perfil.as_view(template_name='perfil.html'), name='perfil'),
    path('criarconta/', Criarconta.as_view(template_name='criarconta.html'), name='criarconta'),
    path('editarperfil/<int:pk>', Editarperfil.as_view(template_name='editarperfil.html'), name='editarperfil'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name='editarperfil.html',
                                                             success_url=reverse_lazy('financeiro:financeiro')
                                                             ), name='mudarsenha'),
]

hpinicial/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class Tenant(models.Model):
    nome = models.CharField(max_length=255, unique=True)
    subdomain = models.CharField(max_length=255, unique=True)
    cnpj = models.CharField(max_length=255, unique=True, null=True, blank=True)
    ativo = models.BooleanField(null=True, blank=True)

    def __str__(self):
        return self.nome


class Usuario(AbstractUser):
    tenant = models.ForeignKey(Tenant, null=True, on_delete=models.CASCADE)
    cnpj_empresa = models.CharField(max_length=18)

hpinicial/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms

class Cricarcontaform(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')

hpinicial/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import Cricarcontaform
from .models import Usuario

# Create your views here.

class Homepagelogin(TemplateView):
    template_name = 'login.html'

class Perfil(LoginRequiredMixin, DetailView):
    template_name = 'perfil.html'
    model = Usuario

    def get_success_url(self):
        return reverse('financeiro:financeiro')

class Criarconta(FormView):
    template_name = 'criarconta.html'
    form_class = Cricarcontaform

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('financeiro:financeiro')

class Editarperfil(LoginRequiredMixin, UpdateView):
    template_name = 'editarperfil.html'
    model = Usuario
    fields = ['first_name', 'last_name', 'email', 'cpf']

    def get_success_url(self):
        return reverse('financeiro:financeiro')

hpinicial/templates/criarconta.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Criar Conta
{% endblock %}

{% block content %}

    <header class="py-36 flex justify-between items-center">
        <div class="w-3/5 text-violet-900 text-center flex items-center flex-col">
            <a href="https://www.instagram.com/sigarumoaonorte?igsh=NjJrYTJieXRhN3Nl" target="_blank"><div class="text-center flex items-center"><ion-icon name="logo-instagram"></ion-icon>Siga-nos no Instagram</div></a>
            <br>
            <a href="https://rumoaonorte.com.br/" target="_blank"><div class="text-center flex items-center"><ion-icon name="globe-outline"></ion-icon>Visite nosso site</div></a>
            <br>
            <a href=""><div class="text-center flex items-center"><ion-icon name="logo-whatsapp"></ion-icon>Alguma dúvida? Fale conosco</div></a>
        </div>
        <div class="w-2/5 text-gray-700 text-center text-xs flex items-center flex-col">
            <form method="post">
               {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4 text-xl">Crie uma conta para continuar</legend>
                   {{ form|crispy }}
                </fieldset>
                <button class="bg-violet-600 hover:bg-violet-800 text-white py-1 my-2 px-3 w-full md:text-lg rounded-md" type="submit">Criar Conta</button>
            </form>
        </div>
    </header>
    <footer class="w-full px-5 py-4 bg-violet-200">
        <ul class="flex justify-between items-center">
            <li>&copy; 2024 </li>
            <li> <ion-icon name="telescope-outline"></ion-icon> Te ajudando a chegar no seu norte <ion-icon name="sparkles-outline"></ion-icon></li>
            <li>Control Norte</li>
        </ul>
    </footer>
{% endblock %}

hpinicial/templates/editarperfil.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Editar Perfil
{% endblock %}

{% block content %}
<main class="py-20 px-10">
    <div class="py-2 px-4 text-2xl text-violet-900 text-center">Editar Perfil</div>
    <div class="flex felx-nowrap">
        <div class="container w-4/5 bg-violet-100 p-8 rounded text-violet-800 ">
                <div><h1 class="text-xl py-2 text-violet-900">{{ object.first_name }} {{ object.last_name }}</h1></div>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <a href="homepageinicial:perfil">
                        <button class="bg-violet-600 hover:bg-violet-800 text-white py-1 my-2 px-3 md:text-lg rounded-md" type="submit">Salvar</button>
                    </a>
                </form>
                <small><a href="{% url 'homepageinicial:mudarsenha' %}">Quer mudar sua senha?</a></small>
        </div>
    </div>
</main>
{% endblock %}

hpinicial/templates/logged_out.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Logout
{% endblock %}

{% block content %}
   <header class="min-h-screen flex justify-center items-center bg-no-repeat">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h2 class="text-2xl text-violet-800">Você saiu da sua conta</h2>
            <div class="flex flex-nowrap justify-center space-x-5 p-5">
            <a href="{% url 'homepageinicial:login' %}"><button class="bg-violet-600 hover:bg-violet-800 text-white py-1 my-2 px-3 w-full md:text-lg rounded-md" type="submit">Fazer Login</button></a>
            <a href="{% url 'homepageinicial:criarconta' %}"><button class="bg-violet-600 hover:bg-violet-800 text-white py-1 my-2 px-3 w-full md:text-lg rounded-md" type="submit">Criar uma Conta</button></a>
            </div>
        </div>
    </header>
    <footer class="w-full px-5 py-4 bg-violet-200">
        <ul class="flex justify-between items-center">
            <li>&copy; 2024 </li>
            <li> <ion-icon name="telescope-outline"></ion-icon> Te ajudando a chegar no seu norte <ion-icon name="sparkles-outline"></ion-icon></li>
            <li>Control Norte</li>
        </ul>
    </footer>
{% endblock %}

hpinicial/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Fazer Login
{% endblock %}

{% block content %}
    <header class="py-36 flex justify-between items-center">
        <div class="w-3/5 text-violet-900 text-center flex items-center flex-col">
            <a href="https://www.instagram.com/sigarumoaonorte?igsh=NjJrYTJieXRhN3Nl" target="_blank"><div class="text-center flex items-center"><ion-icon name="logo-instagram"></ion-icon>Siga-nos no Instagram</div></a>
            <br>
            <a href="https://rumoaonorte.com.br/" target="_blank"><div class="text-center flex items-center"><ion-icon name="globe-outline"></ion-icon>Visite nosso site</div></a>
            <br>
            <a href=""><div class="text-center flex items-center"><ion-icon name="logo-whatsapp"></ion-icon>Alguma dúvida? Fale conosco</div></a>
        </div>
        <div class="w-2/5 text-gray-700 text-start flex items-center flex-col">
            <div class="py-4 px-4">
                <form method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Entrar</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <button class="bg-violet-600 hover:bg-violet-800 text-white py-1 my-2 px-3 w-full md:text-lg rounded-md" type="submit">Entrar</button>
                </form>
                <small>
                    Não tem uma conta ainda? <p><a href="{% url 'homepageinicial:criarconta' %}">Clique aqui para criar uma conta</a></p>
                </small>
            </div>
        </div>
    </header>
    <footer class="w-full px-5 py-4 bg-violet-200">
        <ul class="flex justify-between items-center">
            <li>&copy; 2024 </li>
            <li> <ion-icon name="telescope-outline"></ion-icon> Te ajudando a chegar no seu norte <ion-icon name="sparkles-outline"></ion-icon></li>
            <li>Control Norte</li>
        </ul>
    </footer>
{% endblock %}

hpinicial/templates/perfil.html
{% extends 'base.html' %}
{% block titulo %}
Meu Perfil
{% endblock %}

{% block content %}
<main>
    <section>
        <div class="py-20 px-20">
            <div class="flex felx-nowrap justify-between">
                <div><h1 class="text-3xl py-2 text-violet-900">{{ object.first_name }} {{ object.last_name }}</h1></div>
                <div class="content-center flex felx-nowrap p-2">
                    <a href="{% url 'homepageinicial:editarperfil' request.user.pk %}">
                        <button class="bg-transparent text-violet-700 hover:text-black flex flex-nowrap">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z"/>
                            </svg>
                        </button>
                    </a>
                    <form id="logout-form" method="post" action="{% url 'homepageinicial:logout' %}">
                        {% csrf_token %}
                        <button class="bg-transparent text-violet-700 font-semibold hover:text-black py- px-4 rounded">
                            <ion-icon name="log-out-outline"></ion-icon> Sair
                        </button>
                    </form>
                </div>
            </div>
            <div class="grid grid-cols-5">
                <div class="col-start-1 col-span-3">
                    <div class="flex flex-nowrap grid grid-cols-2">
                        <div class="flex flex-nowrap">
                            <div class="content-start py-2 px-2 text-violet-900">Usuário: </div>
                            <div class="content-start  text-gray-700 py-2">{{ object.username }}</div>
                        </div>
                        <div class="flex flex-nowrap">
                            <div class="content-start py-2 px-2 text-violet-900">CPF: </div>
                            <div class="content-start text-gray-700 py-2">{{ object.cpf }}</div>
                        </div>
                    </div>
                    <hr>
                    <div class="flex flex-nowrap justify-between">
                         <div class="flex flex-nowrap">
                            <div class="content-start text-sm py-2 px-2 text-violet-900">E-mail: </div>
                            <div class="content-start text-sm text-gray-700 py-2">{{ object.email }}</div>
                         </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}