ControlNorte/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cliente/', include('cliente.urls', namespace='cliente')),
    path('hpinicial/', include('hpinicial.urls', namespace='homepageinicial')),
    path('', include('financeiro.urls', namespace='fianceiro')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cliente/urls.py
from django.urls import path, include
from cliente import views
from .views import *

app_name = 'cliente'

urlpatterns = [
    path('', Cliente.as_view(), name='cliente'),
    path('<int:pk>/', Destalhesclientes.as_view(), name='detalhesclientes'),
    path('cadastrarcliente/', cadastrarcliente, name='cadastrarcliente'),
    path('editar/<int:pk>/', Editarcliente.as_view(template_name='editarcliente.html'), name='editarcliente'),
    path('download_modelo_importacao/', views.download_modelo_importacao_cadastro_cliente, name='download_modelo_importacao_cadastro_cliente'),
]

cliente/models.py
from django.db import models
from hpinicial.managers import TenantManager
from hpinicial.models import Tenant


LISTA_ESTADOS = (
        ('AC','Acre'),
        ('AL','Alagoas'),
        ('AP','Amapá'),
        ('AM','Amazonas'),
        ('BA','Bahia'),
        ('CE','Ceará'),
        ('ES','Espírito Santo'),
        ('GO','Goiás'),
        ('MA','Maranhão'),
        ('MT','Mato Grosso'),
        ('MS','Mato Grosso do Sul'),
        ('MG','Minas Gerais'),
        ('PA','Pará'),
        ('PB','Paraíba'),
        ('PR','Paraná'),
        ('PE','Pernambuco'),
        ('PI','Piauí'),
        ('RJ','Rio de Janeiro'),
        ('RN','Rio Grande do Norte'),
        ('RS','Rio Grande do Sul'),
        ('RO','Rondônia'),
        ('RR','Roraima'),
        ('SC','Santa Catarina'),
        ('SP','São Paulo'),
        ('SE','Sergipe'),
        ('TO','Tocantins'),
        ('DF','Distrito Federal'),
)

LISTA_RAMOS = (
    ('ALIMENTAÇÃO','Alimentação'),
    ('INDUSTRIA','Indústria'),
    ('COMERCIO','Comércio'),
    ('SAUDE','Saúde'),
    ('SERVICOS','Serviços')
)


class Ramo(models.Model):
    nome = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.nome


class cadastro_de_cliente(models.Model):
    tenant = models.ForeignKey(Tenant, null=True, on_delete=models.CASCADE)
    razao_social = models.CharField(max_length=100, null=True, blank=True)
    cnpj = models.CharField(max_length=100, null=True, blank=True)
    logadouro = models.CharField(max_length=100, null=True, blank=True)
    bairro = models.CharField(max_length=100, null=True, blank=True)
    número = models.IntegerField(null=True, blank=True)
    cidade = models.CharField(max_length=100, null=True, blank=True)
    estado = models.CharField(max_length=100, choices=LISTA_ESTADOS, null=True, blank=True)
    pessoa_de_contato = models.CharField(max_length=100, null=True, blank=True)
    telefone = models.CharField(max_length=100, null=True, blank=True)
    email_contato = models.CharField(max_length=100, null=True, blank=True)
    ramo = models.ForeignKey(Ramo, null=True, on_delete=models.SET_NULL)
    ativo = models.BooleanField(default=True)
    bancos_utilizados = models.CharField(max_length=100, null=True, blank=True)
    servicos_contratados = models.CharField(max_length=100, null=True, blank=True)
    responsavel_conciliacao = models.CharField(max_length=100, null=True, blank=True)
    responsavel_apresentacao = models.CharField(max_length=100, null=True, blank=True)
    funcionarios = models.TextField(max_length=500, null=True, blank=True)
    contas_fixas = models.TextField(max_length=500, null=True, blank=True)
    classificacoes = models.TextField(max_length=500, null=True, blank=True)
    principais_fornecedores = models.TextField(max_length=500, null=True, blank=True)
    observacoes = models.TextField(max_length=500, null=True, blank=True)
    sugestoes = models.TextField(max_length=500, null=True, blank=True)
    historico = models.TextField(max_length=500, null=True, blank=True)
    criado_em = models.DateTimeField(auto_now_add=True)
    data_inicio_plano = models.DateTimeField(null=True, blank=True, default=None)
    tempo_plano = models.CharField(max_length=100, null=True, blank=True, default=None)
    data_final_plano = models.DateTimeField(null=True, blank=True, default=None)
    tempo_plano1 = models.CharField(max_length=100, null=True, blank=True, default=None)

    objects = TenantManager()

    def __str__(self):
        return self.razao_social

cliente/forms.py
from django import forms
from .models import cadastro_de_cliente, LISTA_ESTADOS, LISTA_RAMOS

class Cadastrodeclientes(forms.ModelForm):

    class Meta:
        model = cadastro_de_cliente
        fields = "__all__"
        widgets = {'razao_social': forms.TextInput(attrs={'class': 'form-control'}),
                  'cnpj': forms.NumberInput(attrs={'class': 'form-control'}),
                  'logadouro': forms.TextInput(attrs={'class': 'form-control'}),
                  'bairro': forms.TextInput(attrs={'class': 'form-control'}),
                  'número': forms.NumberInput(attrs={'class': 'form-control'}),
                  'cidade': forms.TextInput(attrs={'class': 'form-control'}),
                  'estado': forms.Select(choices=LISTA_ESTADOS, attrs={'class': 'form-control'}),
                  'pessoa_de_contato': forms.TextInput(attrs={'class': 'form-control'}),
                  'telefone': forms.NumberInput(attrs={'class': 'form-control'}),
                  'email_contato': forms.EmailInput(attrs={'class': 'form-control'}),
                  'ramo': forms.Select(choices=LISTA_RAMOS, attrs={'class': 'form-control'}),
                  'bancos_utilizados': forms.TextInput(attrs={'class': 'form-control'}),
                  'servicos_contratados': forms.TextInput(attrs={'class': 'form-control'}),
                  'responsavel_conciliacao': forms.TextInput(attrs={'class': 'form-control'}),
                  'responsavel_apresentacao': forms.TextInput(attrs={'class': 'form-control'}),
                  'funcionarios': forms.Textarea(attrs={'class': 'form-control'}),
                  'contas_fixas': forms.Textarea(attrs={'class': 'form-control'}),
                  'classificacoes': forms.Textarea(attrs={'class': 'form-control'}),
                  'principais_fornecedores': forms.Textarea(attrs={'class': 'form-control'}),
                  'observacoes': forms.Textarea(attrs={'class': 'form-control'}),
                  'sugestoes': forms.Textarea(attrs={'class': 'form-control'}),
                  'historico': forms.Textarea(attrs={'class': 'form-control'}),
                  
        }

cliente/views.py
from django.shortcuts import render, reverse, HttpResponseRedirect
from .models import *
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import Cadastrodeclientes
from django.http import FileResponse
import openpyxl
from io import BytesIO
from django.db import transaction
from django.shortcuts import redirect
from django.contrib import messages
import pandas as pd
from django.http import JsonResponse
from financeiro.teste import UploadFileForm
from .utils import importar_clientes


# Create your views here.
# def cliente(request):
#     return render(request,'cliente.html')

class Cliente(LoginRequiredMixin, ListView):
    template_name = 'cliente.html'
    model = cadastro_de_cliente

    def get_queryset(self):
        termo_pesquisa = self.request.GET.get('query')
        if termo_pesquisa:
            object_list = self.model.objects.filter(razao_social__icontains=termo_pesquisa)
            return object_list
        else:
            return self.model.objects.all


class Destalhesclientes(LoginRequiredMixin, DetailView):
    template_name = 'detalhesclientes.html'
    model = cadastro_de_cliente
    context_object_name = 'cliente'


def cadastrarcliente(request):
    file = ""
    importar = ""
    form = UploadFileForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        file = request.FILES['file']
        importar = importar_clientes(arquivo_importacao_cliente=file,tenant=request.tenant)
        print(f'Erro: {importar}')

    if not file:
        if request.method == 'POST':
            dados = request.POST.dict()

            ramo_id = dados.get('ramo')
            ramo = Ramo.objects.filter(id=ramo_id).first() if ramo_id else None

            novocliente = cadastro_de_cliente.objects.create(razao_social=dados.get('razao'), cnpj=dados.get('cnpj'),
                                                            logadouro=dados.get('logadouro'),bairro=dados.get('bairro'),
                                                            número=dados.get('número'), cidade=dados.get('cidade'),
                                                            estado=dados.get('estado'), pessoa_de_contato=dados.get('pessoa'),
                                                            telefone=dados.get('telefone'), email_contato=dados.get('email'),
                                                            ramo=ramo,
                                                            bancos_utilizados=dados.get('bancos'),
                                                            servicos_contratados=dados.get('servicos'),
                                                            responsavel_conciliacao=dados.get('conciliacao'),
                                                            responsavel_apresentacao=dados.get('apresentacao'),
                                                            funcionarios=dados.get('funcionarios'),
                                                            contas_fixas=dados.get('fixas'),
                                                            classificacoes=dados.get('classificacoes'),
                                                            principais_fornecedores=dados.get('fornecedores'),
                                                            observacoes=dados.get('observacoes'),
                                                            sugestoes=dados.get('sugestoes'),
                                                            historico=dados.get('historico'),
                                                            tenant=request.tenant)
            novocliente.save()

    ramos = Ramo.objects.all()

    context = {'ramos': ramos, 'form': form, 'importar': importar}

    return render(request, 'cadastrarcliente.html', context)

class Cadastrarcliente(LoginRequiredMixin, FormView):
    form_class = Cadastrodeclientes
    template_name = 'cadastrarcliente.html'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('cliente:cliente')


class Editarcliente(LoginRequiredMixin, UpdateView):
    template_name = 'editarcliente.html'
    model = cadastro_de_cliente
    fields = '__all__'

    def get_success_url(self):
        return reverse('cliente:cliente')


def download_modelo_importacao_cadastro_cliente(request):
    # Criar um arquivo Excel em memória
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Modelo de Importação"

    # Obter os campos do model CadastroClientes
    fields = [field.name for field in cadastro_de_cliente._meta.fields]
    # Verificando se o campo existe antes de remover
    for field in ['id', 'tenant', 'historico', 'criado_em', 'servicos_contratados', 'ativo', 'ramo']:
        if field in fields:
            fields.remove(field)
    # Escrever os nomes dos campos na primeira linha
    for col_num, field in enumerate(fields, 1):
        ws.cell(row=1, column=col_num, value=field)

    # Salvar o arquivo Excel em memória
    output = BytesIO()
    wb.save(output)
    output.seek(0)

    # Retornar o arquivo como resposta para download
    return FileResponse(output, as_attachment=True, filename='modelo_importacao_clientes.xlsx')

cliente/templates/cadastrarcliente.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head %}
<style>
    .container {
        background-color: #ede9fe;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        max-width: 800px;
        width: 100%;
    }
    h1 {
        text-align: center;
        color: #333;
    }
    .form-group {
        margin-bottom: 15px;
    }
    label {
        display: block;
        margin-bottom: 5px;
        color: #555;
    }
    .row {
        display: flex;
        gap: 10px;
    }
    .row .form-group {
        flex: 1;
    }
    input {
        padding-left: 12px;
        margin: 8px;
    }
    input, select, textarea {
        width: 100%;
        padding-left: 12px;
        margin: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        height: 30px
    }
    input:focus, select:focus, textarea:focus {
        border-color: #5a2d9b;
        outline: none;
    }

    /* Estilo para o popup */
        #popup {
            display: none; /* Esconde o popup por padrão */
            position: fixed;
            bottom: 20px;
            right: 20px;
            background-color: rgba(0, 0, 0, 0.8);
            color: white;
            padding: 15px 20px;
            border-radius: 8px;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2);
            z-index: 1000; /* Garante que o popup ficará acima de outros elementos */
        }
</style>

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}

{% block titulo %}
Cadastrar Cliente
{% endblock %}

{% block content %}
<main>
    <section class="p-20">
        <div class="container w-10/12">
            <div class="flex flex-nowrap justify-between">
                <div class="text-3xl text-violet-900">Cadastro de Cliente</div>
            </div>
            <button class="bg-violet-600 hover:bg-violet-800 text-white py-1 my-2 px-3 md:text-lg rounded-md" type="button" data-bs-toggle="modal" data-bs-target="#importModal">
                Importar
            </button>
            <br>
            <form method="POST">
            {% csrf_token %}
            <div class="text-xl text-violet-900">Dados cadastrais</div>
            <div class="form-group">
                <label for="razao">Razão Social:</label>
                <input type="text" id="razao" name="razao"/>
            </div>
            <div class="row">
                <div class="form-group">
                    <label for="cnpj">CNPJ:</label>
                    <input type="text" id="cnpj" name="cnpj"/>
                </div>
                <div class="form-group">
                    <label>Ramo:</label>
                    <select name="ramo">
                        {% for ramo in ramos %}
                            <option value="{{ ramo.id }}">{{ ramo.nome }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            
            <div class="form-group">
                <label for="endereco">Endereço:</label>
                <input type="text" id="endereco" name="logadouro"/>
            </div>
            <div class="row">
                <div class="form-group">
                    <label for="numero">Número:</label>
                    <input type="text" id="numero" name="número"/>
                </div>
                <div class="form-group">
                    <label for="bairro">Bairro:</label>
                    <input type="text" id="bairro" name="bairro"/>
                </div>
                <div class="form-group">
                    <label for="cidade">Cidade:</label>
                    <input type="text" id="cidade" name="cidade"/>
                </div>
                <div class="form-group">
                    <label for="estado">Estado:</label>
                    <input type="text" id="estado" name="estado"/>
                </div>
            </div>
            <br>
            <div class="text-xl text-violet-900">Contato</div>
            <div class="row">
                <div class="form-group">
                    <label for="pessoa_contato">Pessoa de Contato:</label>
                    <input type="text" id="pessoa_contato" name="pessoa"/>
                </div>
                <div class="form-group">
                    <label for="telefone">Telefone:</label>
                    <input type="text" id="telefone" name="telefone"/>
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email"/>
                </div>
            </div>
            <br>
            <div class="text-xl text-violet-900">Outras informações</div>
            <div class="row">
                <div class="form-group">
                    <label for="bancos">Bancos:</label>
                    <input type="text" id="bancos" name="bancos"/>
                </div>
                <div class="form-group">
                    <label for="servicos">Serviços:</label>
                    <input type="text" id="servicos" name="servicos"/>
                </div>
                <div class="form-group">
                    <label for="conciliacao">Conciliação:</label>
                    <input type="text" id="conciliacao" name="conciliacao"/>
                </div>
                <div class="form-group">
                    <label for="reunioes">Reuniões:</label>
                    <input type="text" id="reunioes" name="apresentacao"/>
                </div>
            </div>
            
            <div class="row">
                <div class="form-group">
                    <label for="funcionarios">Funcionários:</label>
                    <input type="text" id="funcionarios" name="funcionarios"/>
                </div>
                <div class="form-group">
                    <label for="contas_fixas">Contas Fixas:</label>
                    <input type="text" id="contas_fixas" name="fixas"/>
                </div>
            </div>
            
            <div class="row">
                <div class="form-group">
                    <label for="classificacoes">Classificações:</label>
                    <input type="text" id="classificacoes" name="classificacoes"/>
                </div>
                <div class="form-group">
                    <label for="fornecedores">Principais Fornecedores:</label>
                    <input type="text" id="fornecedores" name="fornecedores"/>
                </div>
            </div>
            
            <div class="row">
                <div class="form-group">
                    <label for="observacoes">Observações:</label>
                    <input type="text" id="observacoes" name="observacoes"/>
                </div>
                <div class="form-group">
                    <label for="sugestoes">Sugestões:</label>
                    <input type="text" id="sugestoes" name="sugestoes"/>
                </div>
            </div>
            
            <div class="form-group">
                <label for="historico">Histórico:</label>
                <textarea id="historico" rows="4" name="historico"></textarea>
            </div>
            <div class="flex flex-nowrap justify-between">
                <div class="flex flex-nowrap">
                    <label class="pr-2" for="ativobanco">Ativo:</label>
                    <input type="checkbox" id="ativobanco" name="ativo" value="True">
                </div>
                <button class="bg-violet-600 hover:bg-violet-800 text-white py-1 my-2 px-3 md:text-lg rounded-md" type="submit">Enviar</button>
            </div>
            </form>
        </div>
    </section>
</main>
<div class="modal fade" id="importModal" tabindex="-1" aria-labelledby="importModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="importModalLabel">Importar Dados</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-body">
                <p>Faça o download do modelo de importação e selecione ou arraste o arquivo para importar:</p>

                <!-- Botão para download do modelo -->
                <a href="{% url 'cliente:download_modelo_importacao_cadastro_cliente' %}" class="btn btn-primary">Baixar modelo de importação</a>

                <br><br>

                <!-- Campo para upload -->

                <div class="mb-3">
                    <label class="form-label">Selecione o arquivo para importação</label>
                    {{ form.as_p }}
                </div>

                <!-- Campo para arrastar e soltar o arquivo -->
                <div class="dropzone" style="border: 2px dashed #ccc; padding: 20px; text-align: center;">
                    Arraste o arquivo aqui
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <button type="submit" class="btn btn-primary">Importar</button>
            </div>
            </form>
        </div>
    </div>
</div>

<!-- Popup -->
<div id="popup">
    {{ importar }}
</div>

<script>
    // Verifica se há uma mensagem na variável 'importar'
    const popup = document.getElementById("popup");
    if ("{{ importar }}") {
        popup.style.display = "block"; // Exibe o popup
        setTimeout(() => {
            popup.style.display = "none"; // Esconde após 3 segundos
        }, 3000); // 3000 milissegundos = 3 segundos
    }
</script>
{% endblock %}

cliente/templates/cliente.html
{% extends 'base.html' %}

{% block titulo %}
Cliente
{% endblock %}

{% block content %}

<main class="py-20 px-10">
    <div class="py-2 px-4 text-2xl text-violet-900">Resumo</div>
    <div class="flex flex-nowrap">
        <div class="w-4/5 px-2">
            <div class="flex flex-nowrap justify-center gap-2">
                    <div class="h-64 w-2/5 bg-violet-100 hover:bg-violet-300 font-semibold text-lg text-violet-700 text-center">
                        <div>Tipos de Clientes</div>
                    </div>
                    <div class="h-64 w-3/5 bg-violet-100 hover:bg-violet-300 font-semibold text-lg text-violet-700 text-center">
                        <div>Clientes Ativos</div>
                    </div>
            </div>
            <div class="flex flex-nowrap justify-center gap-2 pt-2 ">
                     <div class="h-64 w-3/5 bg-violet-100 hover:bg-violet-300 font-semibold text-lg text-violet-700 text-center">
                        <div>Satisfação do Cliente</div>
                    </div>
                     <div class="h-64 w-2/5 bg-violet-100 hover:bg-violet-300 font-semibold text-lg text-violet-700 text-center">
                        <div>Pincipais Serviços</div>
                    </div>
            </div>
        </div>
        <div class="w-1/5 py-2 bg-violet-100 hover:bg-violet-300 font-semibold text-lg text-violet-700 text-center"> Ultímos CLientes
        </div>
    </div>
    <br>
    <div>
        <div class="px-2 grid grid-cols-3 items-center">
            <div class="px-4 text-2xl py-2 text-violet-900">Clientes</div>
            <form method="get" class="flex justify-center">
                <input type="text"
                       type="submit"
                       class="content-center outline-transparent font-semibold px-4 rounded-md text-gray-700"
                       value="{{ request.GET.query }}"
                       name="query"
                       placeholder="Pesquisar...">
                <button class="bg-transparent text-violet-700 hover:text-black text-xl font-semibold px-4 rounded"><ion-icon name="search-outline"></ion-icon></ion-icon></button>
            </form>
            <div class="mr-2 content-center flex justify-end">
                <a href="{% url 'cliente:cadastrarcliente' %}">
                    <button class="bg-transparent text-violet-700 font-semibold hover:text-black px-4 rounded">
                       <ion-icon name="add-outline"></ion-icon> Cadastrar
                    </button>
                </a>
            </div>
        </div>
    </div>
    <hr>
    <section class="py-4">
                <div class="flex flex-nowrap grid grid-cols-4 gap-2 pt-2">
                    {% for cliente in object_list %}
                    <div class="px-2 py-2 bg-violet-200 hover:bg-violet-300 text-center text-violet-800">
                        <a href="{% url 'cliente:detalhesclientes' cliente.pk %}">
                            {{ cliente.razao_social }}<br>
                            {{ cliente.cnpj }}
                        </a>
                    </div>
                    {% endfor %}
                </div>
    </section>
</main>
{% endblock %}

cliente/templates/editarcliente.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block titulo %}
Editar Cliente
{% endblock %}

{% block content %}
<main class="py-20 px-10">
    <div class="py-2 px-4 text-2xl text-violet-900 text-center">Editar Cliente</div>
    <div class="flex felx-nowrap">
        <div class="container w-4/5 bg-violet-100 p-8 rounded text-violet-800 ">
                <div><h1 class="text-xl py-2 text-violet-900">{{ object.razao_social }}</h1></div>
                <form method="post">
                    {% csrf_token %}
                        {{ form|crispy }}
                    <a href='cliente:cliente'><button class="bg-violet-600 hover:bg-violet-800 text-white py-1 my-2 px-3 md:text-lg rounded-md" type="submit">Salvar</button>
                    </a>
                </form>
        </div>
    </div>
</main>
{% endblock %}